"""remove main serie field

Revision ID: 04cc8ae8f5fe
Revises: 3709c16d154c
Create Date: 2022-02-27 21:42:21.248612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cc8ae8f5fe'
down_revision = '3709c16d154c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abilities', 'is_main_series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abilities', sa.Column('is_main_series', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
