"""remove main serie field

Revision ID: 28fef8e97d6f
Revises: 04cc8ae8f5fe
Create Date: 2022-02-27 21:46:19.442562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fef8e97d6f'
down_revision = '04cc8ae8f5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
