"""fix many to many

Revision ID: b29141b41c2e
Revises: 28fef8e97d6f
Create Date: 2022-02-27 21:53:20.165133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29141b41c2e'
down_revision = '28fef8e97d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
